---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
- Пользователь должен иметь возможность удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
- Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге

non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
- Корзина хранится в сессии браузера

implicit:
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
